import Head from 'next/head'
import Hero from './components/Hero'
import Slider from './components/Slider'
import React from 'react'
import Category from './components/Category'

function Home() {
  return (
    <div >
      <Head>
        <title>Charles Cantin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       </Head>
      {/* components */}
      <Hero 
        heading1='Charles Cantin'
        heading2= 'Photographe'
        message="”La photographie, c'est l'art de peindre sans pinceau.”"
        
      />
        <Slider />
      <Category />
    </div>
  )
}

export default Home